export const GETBOOKSUGGESTIONBYPAGE = "GETBOOKSUGGESTIONBYPAGE";
export const GETBOOKSUGGESTIONBYPAGELENGTH = "GETBOOKSUGGESTIONBYPAGELENGTH";

export const TRACKORDER = "TRACKORDER";
export const TRACK_ORDER = "TRACK_ORDER";
export const ADDRESSVERIFICATION = 'ADDRESSVERIFICATION';
// Action for Api to get Books
export const GET_COMPEXAM = "GET_COMPEXAM";
export const GET_FRICTION = "GET_FRICTION";
export const GET_SCHOOLBOOK = "GET_SCHOOLBOOK";
export const GET_UNIVERSITYBOOK = "GET_UNIVERSITYBOOK";
export const GET_BOOK = "GET_BOOK";
export const GET_BOOK_ERR = "GET_BOOK_ERR";
export const GET_ADDRESS = "GET_ADDRESS";
export const SEARCH = "SEARCH";

//Warehouse Action
export const FETCH_WAREHOUSE_DATA = "FETCH_WAREHOUSE_DATA";
export const MAP_WAREHOUSE_DATA = "MAP_WAREHOUSE_DATA";
export const IS_MAP_FILTER = "IS_MAP_FILTER";
export const DATE_WISE_FILTER = "DATE_WISE_FILTER";
export const SEARCH_FILTER = "SEARCH_FILTER";
export const NULL_BARCODE_FILTER = "NULL_BARCODE_FILTER";

//ESCALATE Action
export const FETCH_ESCALATE_DATA = "FETCH_ESCALATE_DATA ";

//Invoice Dashboard
export const FETCH_PURCHASE_INVOICE_DATA = "FETCH_PURCHASE_INVOICE_DATA";
export const FETCH_CREDIT_NOTES_DATA = "FETCH_CREDIT_NOTES_DATA";
export const FETCH_ALL_SUPPLIERS = "FETCH_ALL_SUPPLIERS";
export const FETCH_CREDIT_NOTES_ALL_SUPPLIERS =
  "FETCH_CREDIT_NOTES_ALL_SUPPLIERS";
export const CREATE_NEW_PURCHASE_INVOICE = "CREATE_NEW_PURCHASE_INVOICE";
export const CREATE_NEW_CREDIT_NOTES = "CREATE_NEW_CREDIT_NOTES";
export const CREATE_NEW_SUPPLIER = "CREATE_NEW_SUPPLIER";
export const CREATE_CREDIT_NOTES_NEW_SUPPLIER =
  "CREATE_CREDIT_NOTES_NEW_SUPPLIER";
export const EDIT_INVOICE = "EDIT_INVOICE";
export const EDIT_NOTES = "EDIT_NOTES";

// ----------- home Action
export const GETSEARCH = "GETSEARCH";
export const FETCHSEARCH = "FETCHSEARCH";
export const MAKESEARCHBLANK = "MAKESEARCHBLANK";
export const GETSEARCHGETBOOK = "GETSEARCHGETBOOK";
export const LOADING_SEARCH_SUGGESTION = "LOADING_SEARCH_SUGGESTION";
export const SEARCH_SUGGESTION_FETCHED = "SEARCH_SUGGESTION_FETCHED";
export const ERROR_SEARCH_SUGGESTION = "ERROR_SEARCH_SUGGESTION";
export const NO_SEARCH_SUGGESTION = "NO_SEARCH_SUGGESTION";
export const TOOGLE_GLOBAL_LOADER = "TOOGLE_GLOBAL_LOADER";
export const TOOGLE_GLOBAL_MESSAGE = "TOOGLE_GLOBAL_MESSAGE";
export const CLEAR_SEARCH_SUGGESTION = "CLEAR_SEARCH_SUGGESTION";

// ----------- home Action End

// From Donation part
export const CHANGE_LOGIN = "CHANGE_LOGIN";
export const ADD_DONATION = "ADD_DONATION";
export const CHANAGE_CATEGORIES = "CHANAGE_CATEGORIES";
export const GET_RP_ID = "GET_RP_ID";
export const SETPICKUP = "SETPICKUP";
export const GETDONATIONHISTORY = "GETDONATIONHISTORY";
export const DONATIONMAILDATA = "DONATIONMAILDATA";
export const RESETRPID = "RESETRPID";
export const UPDATE_USER_COMPONENT = "UPDATE_USER_COMPONENT";

// ------------ accountAction

export const LOGIN = "LOGIN";
export const LOGINBACKDROP = "LOGINBACKDROP";

export const SIGNUP = "SIGNUP";
export const SIGNEDUP = "SIGNEDUP";
export const LOGOUT = "LOGOUT";
export const LOGINFAILS = "LOGINFAILS";
export const SHOWLOADER = "SHOWLOADER";
export const SAVEDINFO = "SAVEDINFO";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const CLEARALL = "CLEARALL";
export const CLEARALLUSERSTATUS = "CLEARALLUSERSTATUS";
export const CLEARLOGINERR = "CLEARLOGINERR";
export const ACTIVATESUCCESSPOPUP = "ACTIVATESUCCESSPOPUP";
export const ACTIVATESUCCESSPOPUPOTHER = "ACTIVATESUCCESSPOPUPOTHER";
export const NAVURL = "NAVURL";
export const AFTERLOGINREDIRECT = "AFTERLOGINREDIRECT";
export const CLEARAFTERLOGINREDIRECT = "CLEARAFTERLOGINREDIRECT";
export const OTP_SUCCESS_REQUEST = "OTP_SUCCESS_REQUEST";
export const OTP_FALIURE_REQUEST = "OTP_FALIURE_REQUEST";
export const OTP_SUCCESS_VERIFY = "OTP_SUCCESS_VERIFY";
export const OTP_FALIURE_VERIFY = "OTP_FALIURE_VERIFY";
export const USING_MIDDLEWARE = "USING_MIDDLEWARE";
// ------------ accountAction End

// Product
export const SETNEWPRICICNG = "SETNEWPRICICNG";
export const REVIEW_PRODUCT = "REVIEW_PRODUCT";
export const QUESTION_PRODUCT = "QUESTION_PRODUCT";
//CartAction
export const ADDTOCART = "ADDTOCART";
export const POPUPCART = "POPUPCART";
export const closePOPUPCART = "closePOPUPCART";
export const REMOVECART = "REMOVECART";
export const REMOVEALLCART = "REMOVEALLCART";
export const CARTSESSION = "CARTSESSION";
export const SAVELATER = "SAVELATER";
export const ADDCARTPRICE = "ADDCARTPRICE";
export const SENDADDRESSId = "SENDADDRESSId";
export const ORDERDETAILS = "ORDERDETAILS";
export const SETORDERID = "SETORDERID";
export const CANCELORDER = "CANCELORDER";
export const SETRELOADLORDER = "SETRELOADLORDER";
export const WALLETRAZORPAY = "WALLETRAZORPAY";
export const REDIRECTWALLETTOCART = "REDIRECTWALLETTOCART";
export const TOBEADDEDTOCART = "TOBEADDEDTOCARTS";
export const REMOVETOBEADDEDTOCART = "REMOVETOBEADDEDTOCART";
export const REMOVECARTLOGOUT = "REMOVECARTLOGOUT";
export const MOBILECARTREDIRECT = "MOBILECARTREDIRECT";
export const SHOWRZPAYERR = "SHOWRZPAYERR";
export const UPDATEORDERSUCC = "UPDATEORDERSUCC";
export const PAYPALLERROR = "PAYPALLERROR";
export const OUTOFSTOCK = "OUTOFSTOCK";
export const UPDATECART = "UPDATECART";
export const DEDUCTCASHBACK = "DEDUCTCASHBACK";
export const ADDTOCARTATLOGIN = "ADDTOCARTATLOGIN";
export const UPDATE_CART_FROM_LOCALSTORAGE = "UPDATE_CART_FROM_LOCALSTORAGE";
export const UPDATEEXISTINGCARTPRODUCT = "UPDATEEXISTINGCARTPRODUCT";
export const SHOW_ORDER_ERROR = "SHOW_ORDER_ERROR";
export const RESET_OUT_OF_STOCK_BOOKS = "RESET_OUT_OF_STOCK_BOOKS";

// export const CARTSESSION

// Get address
export const GETADDRESS = "GETADDRESS";
export const GETADDRESS_PERPAGE = "GETADDRESS_PERPAGE";
export const GETSELECTEDADDRESS_PERPAGE = "GETSELECTEDADDRESS_PERPAGE";

export const EDITUSER_ADD = "EDITUSER_ADD";
export const UPDATEADDRESS = "UPDATEADDRESS";
export const EDITADDRESS = "EDITADDRESS";
export const DELETEADDRESS = "DELETEADDRESS";
export const GETSELECTEDADDRESS = "GETSELECTEDADDRESS";
export const SETSELECTEDADDRESSBLANK = "SETSELECTEDADDRESSBLANK";

// Get wallet details
export const GETWALLETD = "GETWALLETD";
export const WALLETRECHARGE = "WALLETRECHARGE";
export const SENDWALLETD_RECHARGEMAIL = "SENDWALLETD_RECHARGEMAIL";
export const LOADING_WALLET_SIGNATURE = "LOADING_WALLET_SIGNATURE";
export const GET_WALLET_SIGNATURE = "GET_WALLET_SIGNATURE";
// export const CALCULATEWALLET ='CALCULATEWALLET';

// User details
export const GETUSERD = "GETUSERD";

// User wishlist
export const USERWISHLIST = "USERWISHLIST";
export const SETRELOADWISHLIST = "SETRELOADWISHLIST";

// Mail
export const ADDORDERMAIL = "ADDORDERMAIL";

// upload execel  NewBooks
export const UPLOADINGEXCEL = "UPLOADINGEXCEL";
export const UPLOADEXCEL = "UPLOADEXCEL";
export const UPDATEBYISBN = "UPDATEBYISBN";
export const FETCH_UPLOADED_BOOKS = "FETCH_UPLOADED_BOOKS";
// FAQ
export const FAQ = "FAQ";

//Proud Donar
export const GETDONARDETAILS = "GETDONARDETAILS";
export const GETDONORSEARCHED = "GETDONORSEARCHED";
export const SETRESPONSEMSG = "SETRESPONSEMSG";
export const GLOABALOADER = "GLOABALOADER";
// Category
export const SETCATEGORY = "SETCATEGORY";

export const GETCATEGORY = "GETCATEGORY";

//MainCategory
export const GETMAINCATEGORY = "GETMAINCATEGORY";
export const GETMAINCATEGORY_LOADER = "GETMAINCATEGORY_LOADER";

//firstpage category
export const GETFIRSTCATEGORY = "GETFIRSTCATEGORY";

// firstPAGE SUBCATEGORY
export const GETFIRSTSUBCATEGORY = "GETFIRSTSUBCATEGORY";
export const GETFIRSTFICTIONCATEGOTY = "GETFIRSTFICTIONCATEGOTY";
export const GETFIRSTSCHOOLCATEGOTY = "GETFIRSTSCHOOLCATEGOTY";
export const GETFIRSTUNIVERSITYCATEGOTY = "GETFIRSTUNIVERSITYCATEGOTY";

//MainCategory Filter
export const GETMAINCATEGORYFLTER = "GETMAINCATEGORYFLTER";
export const GETMAINCATEGORYFLTERLOAD = "GETMAINCATEGORYFLTERLOAD";

// ncert filter
export const GETNCERTFILTER = "GETNCERTFILTER";

export const GETNCERTFILTERLOAD = "GETNCERTFILTERLOAD";

export const GETNCERTFILTERCLICKEDLOADER = "GETNCERTFILTERCLICKEDLOADER";

//NO data found

export const NODATAFOUND = "NODATAFOUND";

//filter Loader
export const GETLOADER = "GETLOADER";

//filter Loader
export const GETLOADERFORNCERT = "GETLOADERFORNCERT";
// Orderactions
export const GETORDERD = "GETORDERD";
export const GETUPDATEDORDERD = "GETUPDATEDORDERD";
export const CONVERTORDER = "CONVERTORDER";
export const VIEWORDERDETAILS = "VIEWORDERDETAILS";
export const MAKECANCELMSGBLANK = "MAKECANCELMSGBLANK";
export const CONVERTORDERSENDREQ = "CONVERTORDERSENDREQ";
export const UPDATEPAYMENT = "UPDATEPAYMENT";
export const FETCH_ORDER_BY_ID = "FETCH_ORDER_BY_ID";
export const FETCH_ORDER_BY_ID_ERROR = "FETCH_ORDER_BY_ID_ERROR";
export const LOADING_USER_ORDERS = "LOADING_USER_ORDERS";
// Orderactions Ends

// Passbook details
export const PASSDETAILS = "PASSDETAILS";
// ********************BackednDonation Actions *********************
export const GETDONATIONLIST = "GETDONATIONLIST";
export const CONFIRMORDERLISTLOADING = "CONFIRMORDERLISTLOADING";
export const DONATIONLISTLOADING = "DONATIONLISTLOADING";
export const UPDATEDONATIONBYID = "UPDATEDONATIONBYID";
export const FETCHDONATIONBYID = "FETCHDONATIONBYID";
export const UPDATEDONATION = "UPDATEDONATION";
export const SERACHDONATIONLIST = "SERACHDONATIONLIST";
export const ADD_DONATIONID = "ADD_DONATIONID";
export const DONATIONREFUNDORDER = "DONATIONREFUNDORDER";
// Fetch paid donations
export const GETPAIDDONATIONS = "GETPAIDDONATIONS";
// filter process donation
export const GETPROCESSDONATIONS = "GETPROCESSDONATIONS";
// DONATION NOTES
export const INSERT_DONATION_NOTES = "INSERT_DONATION_NOTES";
export const GET_DONATION_NOTES = "GET_DONATION_NOTES";
export const GET_DONATIONNOTE_LOADER = "GET_DONATIONNOTE_LOADER";
//donoation filter
export const GETFOLLOWUPDONATIONS = "GETFOLLOWUPDONATIONS";
//Pickup exception
export const GETPICKUPEXCEPTIONDONATIONS = "GETPICKUPEXCEPTIONDONATIONS";
export const GETDONATIONS_FILTER_BY_STATE = "GETDONATIONS_FILTER_BY_STATE";

export const FETCH_FEDEX_RATE = "FETCH_FEDEX_RATE";
export const FETCH_FEDEX_PINCODE_SERVICE = "FETCH_FEDEX_PINCODE_SERVICE";

export const FETCH_FEDEX_RATE_ERROR = "FETCH_FEDEX_RATE_ERROR";
export const FETCH_FEDEX_PINCODE_SERVICE_ERROR =
  "FETCH_FEDEX_PINCODE_SERVICE_ERROR";

export const GETDONATIONS_FILTER_BY_STATUS = "GETDONATIONS_FILTER_BY_STATUS";

// ********************BackednDonation Actions *********************

//BackendOffice Actions

// -------------------- BackendOrderOffice Actions ---------------------

export const GETORDERLIST = "GETORDERLIST";
export const UPDATEORDERBYID = "UPDATEORDERBYID";
export const REFUNDORDER = "REFUNDORDER";
export const UPDATEREFUNDORDERBYID = "UPDATEREFUNDORDERBYID";

export const ORDERLISTLOADING = "ORDERLISTLOADING";
export const UPDATESHIPPINGADDRESS = "UPDATESHIPPINGADDRESS";
export const FETCHSHIPPINGADDRESS = "FETCHSHIPPINGADDRESS";
export const FILTERORDER = "FILTERORDER";
export const CLEAR_ORDERLIST = "CLEAR_ORDERLIST";

export const SHIPPINGADDRESSLOADING = "SHIPPINGADDRESSLOADING";
export const GETCONFIRMORDERLIST = "GETCONFIRMORDERLIST";
export const SERACHORDERLIST = "SERACHORDERLIST";
export const RESENTMAIL = "RESENTMAIL";
export const MERGEORDER = "MERGEORDER";
// Loader for merging order
export const MERGINGLOADER = "MERGINGLOADER";

// Get merge order
export const GETMERGEORDER = "GETMERGEORDER";

// Update Order Tracking
export const UPDATE_ORDER_TRACKING = "UPDATE_ORDER_TRACKING";
export const LOADING_UPDATE_ORDER_TRACKING = "LOADING_UPDATE_ORDER_TRACKING";
// get status Verification

export const GETSTATUSVERIFY = "GETSTATUSVERIFY";
export const SERACHORDERLISTSTATUS = "SERACHORDERLISTSTATUS";
export const STATUSLOADER = "STATUSLOADER";

// get Rto

export const ORDERRTO = "ORDERRTO";

export const UPDATERTO = "UPDATERTO";

export const RTOVERIFIED = "RTOVERIFIED";

// verifiedRto
export const VERIFIEDRTO = "VERIFIEDRTO";

//Remove from Rto

export const INSTOCKRTO = "INSTOCKRTO";
export const GET_ESCALATE_LIST = "GET_ESCALATE_LIST";
export const GET_DISPUTED_LIST = "GET_DISPUTED_LIST";
export const CANCILORDER = "CANCILORDER";
export const GETZONES = "GETZONES";
export const CLEAR_GETZONES = "CLEAR_GETZONES";

// --------------------END BackendOrderOffice Actions ---------------------

// export const GETDONATIONLIST = "GETDONATIONLIST";

export const GETWALLETLIST = "GETWALLETLIST";
export const WALLETLISTLOADING = "WALLETLISTLOADING";
export const ADDWALLET = "ADDWALLET";
export const MAKEWALLETREFUNDED = "MAKEWALLETREFUNDED";
export const GETWALLETORDERLIST = "GETWALLETORDERLIST";
export const WALLETORDERLISTLOADING = "WALLETORDERLISTLOADING";
export const ADDORDER = "ADDORDER";
export const REFUNDCONFIRM = "REFUNDCONFIRM";

export const GETDONATIONORDERLIST = "GETDONATIONORDERLIST";
export const DONATIONORDERLISTLOADING = "DONATIONORDERLISTLOADING";
export const ADDDONATION = "ADDDONATION";
export const REFUNDDONATIONCONFIRM = "REFUNDDONATIONCONFIRM";
export const NODONATIONREFUNDCONFIRM = "NODONATIONREFUNDCONFIRM";
export const GETUSERWALLETLIST = "GETUSERWALLETLIST";
//export const WALLETLISTLOADING = "WALLETLISTLOADING";
export const ADDUSERWALLET = "ADDUSERWALLET";

export const NOREFUNDCONFIRM = "NOREFUNDCONFIRM";
export const GETBOOKINVENTORYLIST = "GETBOOKINVENTORYLIST";
export const BOOKINVENTORYLISTLOADING = "BOOKINVENTORYLISTLOADING";
export const FETCHBOOKBYID = "FETCHBOOKBYID";
export const UPDATEBOOK = "UPDATEBOOK";
export const DELETEBOOK = "DELETEBOOK";

export const FETCHINVENTORY = "FETCHINVENTORY";
export const CHANGECURRENTINVENTORY = "CHANGECURRENTINVENTORY";
export const UPDATEBOOKINVENTORY = "UPDATEBOOKINVENTORY";
export const DELETEBOOKINVENTORY = "DELETEBOOKINVENTORY";

// *********************** backendConfirmOrrderAction *************

export const ORDERSLOADING = "ORDERSLOADING";
export const GETORDERS = "GETORDERS";
export const ORDERUPDATE = "ORDERUPDATE";
// export const CANCELORDER = "CANCELORDER"; // Above declared same actionTypes for another page
export const SENDINGEMAIL = "SENDINGEMAIL";
export const SENTEMAIL = "SENTEMAIL";
export const UPDATEORDERBOOKS = "UPDATEORDERBOOKS";
export const UPDATEORDERWEIGHT = "UPDATEORDERWEIGHT";
export const UPDATEBOOKISFIND = "UPDATEBOOKISFIND";
export const CPRECOMMENDATIONS = "CPRECOMMENDATIONS";
export const CPLOADING = "CPLOADING";
export const FETCH_PENDING_COD = "FETCH_PENDING_COD";
export const CLEAR_FETCH_PENDING_COD = "CLEAR_FETCH_PENDING_COD";
//  Get the Token for the ShipRocket
export const SET_SHIPROCKET_TOKEN = "SET_SHIPROCKET_TOKEN";

export const GET_MANIFEST = "GET_MANIFEST";

export const SET_MANIFEST = "SET_MANIFEST";

export const DUPLICATE_ORDERS = "DUPLICATE_ORDERS";
export const CHECKBOOK_STATUS = "CHECKBOOK_STATUS";

export const FETCHING_COURIER_NAME = "FETCHING_COURIER_NAME";
export const FETCHED_COURIER_NAME = "FETCHED_COURIER_NAME";
export const ERROR_FETCHING_COURIER_NAME = "FETERROR_CH_COINGURIER_NAME";

// *********************** End backendConfirmOrrderAction *************

//For Sale Data filteration by both data range and this month
// ********************** TotalsalefilterAction ************************

export const TOTAL_SALE_THIS_MONTH = "TOTAL_SALE_THIS_MONTH";
export const GET_TOTALSALE_BY_DATE_RANGE = "GET_TOTALSALE_BY_DATE_RANGE";
export const HEALTHRACK = "HEALTHRACK";
export const TOTALWALLETAMOUNT = "TOTALWALLETAMOUNT";
export const GOOGLEDATAFETCHED = "GOOGLEDATAFETCHED";
export const CONTACT_DATA_SYNC_SUCCESS = "CONTACT_DATA_SYNC_SUCCESS";
export const CONTACT_DATA_SYNC_FAIL = "CONTACT_DATA_SYNC_FAIL";
export const GET_BOOK_COUNT = "GET_BOOK_COUNT";
export const ORDERS_CONTACT = "ORDERS_CONTACT";
export const DONATION_CONTACT = "DONATION_CONTACT";
// **********************END TotalsalefilterAction ************************
// ---------------------- TotalsalefilterAction ------------------------

//with order id, getting both email id and user id of the user in backoffice wallet

export const GET_EMAIL_AND_USER_ID_IN_WALLET =
  "GET_EMAIL_AND_USER_ID_IN_WALLET";

export const GET_EMAIL_AND_USER_ID_IN_WALLET_ORDER =
  "GET_EMAIL_AND_USER_ID_IN_WALLET_ORDER";

// to get the count of total data entry sale by both this month and date range

export const GET_DATAENTRYSALE_BY_DATE_RANGE =
  "GET_DATAENTRYSALE_BY_DATE_RANGE";

export const GET_DATAENTRYSALE_THIS_MONTH = "GET_DATAENTRYSALE_THIS_MONTH";

// to get tracking id against donation id
export const GET_TRACKINGNO_AGAINST_DONATIONID =
  "GET_TRACKINGNO_AGAINST_DONATIONID";

// to get order details of every order

export const GET_ORDERDETAILS_OF_EVERY_ORDER =
  "GET_ORDERDETAILS_OF_EVERY_ORDER";
export const GET_FAILEDORDERDETAILS_OF_EVERY_ORDER =
  "GET_FAILEDORDERDETAILS_OF_EVERY_ORDER";

export const GET_WALLETORDERDETAILS_OF_EVERY_ORDER =
  "GET_WALLETORDERDETAILS_OF_EVERY_ORDER";

//view details
export const GET_VIEWDETAILS_OF_EVERY_ORDER = "GET_VIEWDETAILS_OF_EVERY_ORDER";

// putting a search in wallet in backoffice, although it is not fully completed till now.

export const SEARCH_IN_WALLET = "SEARCH_IN_WALLET";
export const SEARCH_IN_WALLET_ORDER = "SEARCH_IN_WALLET_ORDER";

// To restock the book (after returning of the book) on each order

export const RESTOCKING_SINGAL_BOOK = "RESTOCKING_SINGAL_BOOK";
export const ORDER_RESTOCKING_SINGAL_BOOK = "ORDER_RESTOCKING_SINGAL_BOOK";
export const RESTOCKING_FAILED_SINGAL_BOOK = "RESTOCKING_FAILED_SINGAL_BOOK";

// Make book outofStock
export const MAKE_BOOK_OUTSTOCK = "MAKE_BOOK_OUTSTOCK";

// To set Meta tag and Title tag to evrey page(url)

export const SEO_GET_DATA = "SEO_GET_DATA";

// To search in Bookinventory backoffice

export const SEARCH_IN_BOOKINVENTORY = "SEARCH_IN_BOOKINVENTORY";

// For filtering books using rackno
export const FILTER_ALL_BOOKS_AGAINST_RACK_NO =
  "FILTER_ALL_BOOKS_AGAINST_RACK_NO";

// For Home Page Category
export const ONCLICK_COMPEXAMS_BOOKS_SCROLLING = "ONCLICK_COMPEXAMS_SCROLLING";

export const ONCLICK_FRICT_BOOKS_SCROLLING = "ONCLICK_FRICT_BOOKS_SCROLLING";

export const ONCLICK_SCHOOL_BOOKS_SCROLLING = "ONCLICK_SCHOOL_BOOKS_SCROLLING";

export const ONCLICK_UNIV_BOOKS_SCROLLING = "ONCLICK_UNIV_BOOKS_SCROLLING";

export const DISCARD_BOOK = "DISCARD_BOOK";

// Fetch Books to send to Google
export const GET_GOOGLE_BOOKS = "GET_GOOGLE_BOOKS";

// Fetch total weight of the order
export const GET_TOTAL_ORDER_WT = "GET_TOTAL_ORDER_WT";

// Save the previous url before going to search
export const SAVE_PREV_URL = "SAVE_PREV_URL";

// Hit the Order tracking url

// Fetch courier deatils for sending email
export const GETCOURIERDETAILS = "GETCOURIERDETAILS";

// Send courier deatils to  email api
export const SENDOURIERDETAILS = "SENDOURIERDETAILS";

// upload execel  NewBooks
// export const UPLOADEXCEL = "UPLOADEXCEL"
// export const UPDATEBYISBN = "UPDATEBYISBN"

// Get Child Category
export const GETCHILDCATEGORY = "GETCHILDCATEGORY";
export const LOADING_GETCHILDCATEGORY = "LOADING_GETCHILDCATEGORY";
export const LOADING_MAINCATEGORY = "LOADING_MAINCATEGORY";
export const SAVETHECLICKEDCATEGORY = "SAVETHECLICKEDCATEGORY";
export const GETFILTERDATA = "GETFILTERDATA";
export const GET_LOCAL_STATE_MAINCATEGORY = "GET_LOCAL_STATE_MAINCATEGORY";

// Svae the ncert page , category , url
export const SAVETHECLICKEDCATEGORYNCERT = "SAVETHECLICKEDCATEGORYNCERT";

export const GETFIRSTNCERTCATEGORY = "GETFIRSTNCERTCATEGORY";

// Loader for Search
export const LOADER_SEARCH = "LOADER_SEARCH";
export const NO_DATA_fOUND_SEARCH = "NO_DATA_fOUND_SEARCH";

//fetch the ordernotes

export const GET_ORDER_NOTES = "GET_ORDER_NOTES";
export const GET_ORDERNOTE_LOADER = "GET_ORDERNOTE_LOADER";

// insert ordernotes

export const INSERT_ORDER_NOTES = "INSERT_ORDER_NOTES";

//Email
export const PROMOEMAIL = "PROMOEMAIL";
export const DISABLEBTN = "DISABLEBTN";
export const DONATIONPAYMAIL = "DONATIONPAYMAIL";

export const SENTPICKUPMAIL = "SENTPICKUPMAIL";

//Upload pickup file
export const UPLOADPICKUPFILE = "UPLOADPICKUPFILE";

// for cod otp
export const CODOTP = "CODOTP";
export const RESENDOTP = "RESENDOTP";

export const OTPLOADER = "OTPLOADER";

// Excel upload for the order page in backoffice

export const LOADING_ORDER_EXCEL = "LOADING_ORDER_EXCEL";
export const ORDER_EXCEL_UPLOADED = "ORDER_EXCEL_UPLOADED";
// for cartpage offer Book
export const OFFERBOOK = "OFFERBOOK";

// for insert offerbook
export const ORDEROFFERBOOK = "ORDEROFFERBOOK";

// Loading Add Address
export const LOADING_ADD_ADDRESS = "LOADING_ADD_ADDRESS";
// for coupon
export const COUPON = "COUPON";

//for redeem coupon
export const REDEEMCOUPON = "REDEEMCOUPON";

//for reset coupon
export const RESETCOUPON = "RESETCOUPON";

// FOR TWAKTO MSG
export const TWAKTO = "TWAKTO";
export const TWAKTOLOADER = "TWAKTOLOADER";

// for fetch Twak to msg
export const FETCHTWAKTO = "FETCHTWAKTO";

// Loading Add Address
export const LOADING_ADDRESS = "LOADING_ADDRESS";
export const LOADING_ADD_ADDRESS_FALSE = "LOADING_ADD_ADDRESS_FALSE";
export const FETCHLOADER = "FETCHLOADER";

// for userRole in backoffice

export const BACKOFFICEROLE = "BACKOFFICEROLE";
export const ACCESSLOADER = "ACCESSLOADER";
export const ORDERBACKOFFICEROLE = "ORDERBACKOFFICEROLE";
export const ORDERACCESSLOADER = "ORDERACCESSLOADER";

// Search filter
export const GETSEARCHFILTERDATA = "GETSEARCHFILTERDATA";
export const SAVETHEFILTERCLICKEDCATEGORY = "SAVETHEFILTERCLICKEDCATEGORY";
export const FILTER_LOADER_SEARCH = "FILTER_LOADER_SEARCH";
export const SEARCH_ERROR = "SEARCH_ERROR";

// credit mail
export const WALLETCREDITMAIL = "WALLETCREDITMAIL";
export const ORDERCREDITMAIL = "ORDERCREDITMAIL";
export const DONATIONCREDITMAIL = "DONATIONCREDITMAIL";
//unmount product state

export const UNMOUNTPRODUCT = "UNMOUNTPRODUCT";

// Author Page
export const GETAUTHORPAGE = "GETAUTHORPAGE";

export const LOADING_AUTHORPAGE = "LOADING_AUTHORPAGE";

export const GETAUTHORPAGE_LOADER = "GETAUTHORPAGE_LOADER";

export const GETAUTHORDATA = "GETAUTHORDATA";

export const FILTER_LOADER_AUTHOR = "FILTER_LOADER_AUTHOR";

export const GETAUTHORFILTERDATA = "GETAUTHORFILTERDATA";

export const AUTHOR_ERROR = "AUTHOR_ERROR";

export const RESETAUTHORDATA = "RESETAUTHORDATA";

export const ENTERSEODATA = "ENTERSEODATA";

export const SUBMITSEODATA = "SUBMITSEODATA";

export const ADDRESSVERIFYLOADER = "ADDRESSVERIFYLOADER";

export const ADDRESSVERIFY = "ADDRESSVERIFY";

export const UPDATEADDRESSVERIFY = "UPDATEADDRESSVERIFY";

export const ADDRESSVERIFIED = "ADDRESSVERIFIED";

export const FETCHING_CART = "FETCHING_CART";
export const FETCHING_CART_PER_PAGE = "FETCHING_CART_PER_PAGE";
export const CARTSESSION_PER_PAGE = "CARTSESSION_PER_PAGE";
export const FETCHING_CART_ERR_PER_PAGE = "FETCHING_CART_ERR_PER_PAGE";
export const FETCHING_CART_ERR = "FETCHING_CART_ERR";
export const CHECK_BOOK_INCART = "CHECK_BOOK_INCART";
// for fetch backoffice dataEntry
export const FETCHDATAFORENTRY = "FETCHDATAFORENTRY";
export const BACKOFFICEDATALOADER = "BACKOFFICEDATALOADER";
export const CHECKRACK = "CHECKRACK";

export const UPADATEDATAENTRY = "UPADATEDATAENTRY";

export const LOADING_UPADATEDATAENTRY = "LOADING_UPADATEDATAENTRY";

export const FETCHNONISBN = "FETCHNONISBN";

export const UPDATESEARCHDATA = "UPDATESEARCHDATA";

export const FETCHDATANONISBNENTRY = "FETCHDATANONISBNENTRY";

export const UPDATENONISBNENTRY = "UPDATENONISBNENTRY";

export const UPDATENONISBNLOADER = "UPDATENONISBNLOADER";

export const CLEARNONISBN = "CLEARNONISBN";

export const REQUEST_SCRAPPING = "REQUEST_SCRAPPING";
export const GET_SCRAPPING_RES = "GET_SCRAPPING_RES";

export const GETDONATION_BACKOFFICE = "GETDONATION_BACKOFFICE";

export const LOADING_GETDONATION_BACKOFFICE = "LOADING_GETDONATION_BACKOFFICE";

export const GET_NULL_DONATION_ID = "GET_NULL_DONATION_ID";

export const LOADING_GET_NULL_DONATION_ID = "LOADING_GET_NULL_DONATION_ID";

export const FETCH_IMG_SELECTOR = "FETCH_IMG_SELECTOR";

export const UPDATE_IMG_SELECTOR = "UPDATE_IMG_SELECTOR";

export const FETCH_NULLDONATIONID = "FETCH_NULLDONATIONID";

export const FIND_DONATION_ID = "FIND_DONATION_ID";

export const TOTALDATA_COUNT = "TOTALDATA_COUNT";

export const QUERY_FORM = "QUERY_FORM";

// export const TOTALDATA_COUNT = 'TOTALDATA_COUNT';

export const AUTHOR_SUGGESTION = "AUTHOR_SUGGESTION";

export const SET_NULL_AUTHOR_SUGGESTION = "SET_NULL_AUTHOR_SUGGESTION";

export const PUBLICATION_SUGGESTION = "PUBLICATION_SUGGESTION";

export const TITLE_SUGGESTION = "TITLE_SUGGESTION";

export const GETIMAGEAGAIN = "GETIMAGEAGAIN";

export const PUSHPREFFETCH_DATA = "PUSHPREFFETCH_DATA";
export const STUDY_MATERIAL_IMAGES = "STUDY_MATERIAL_IMAGES";
// --------------------START getBooksAction
export const FETCH_GET_BOOKS = "FETCH_GET_BOOKS";

export const FILTER_GET_BOOKS = "FILTER_GET_BOOKS";

export const NOT_FOUND_GET_BOOKS = "NOT_FOUND_GET_BOOKS";

export const LOADING_GETBOOKS = "LOADING_GETBOOKS";

export const GET_LOCAL_STATE_GET_BOOKS = "GET_LOCAL_STATE_GET_BOOKS";
// --------------------END getBooksAction

export const FETCH_USERS_DETAIL = "FETCH_USERS_DETAIL";

export const UPDATE_USER_DETAIL = "UPDATE_USER_DETAIL";

export const LOGIN_TOGGLE = "LOGIN_TOGGLE";

// Address slider

export const ADDRESS_SLIDER = "ADDRESS_SLIDER";

export const LOGIN_DONE_MSG = "LOGIN_DONE_MSG";

// *******************coursesAction***************

export const FETCH_TOPIC_SUCCESS = "FETCH_TOPIC_SUCCESS";

export const FETCH_TOPIC_FAIL = "FETCH_TOPIC_FAIL";

export const FETCH_SUBTOPIC_SUCCESS = "FETCH_SUBTOPIC_SUCCESS";

export const FETCH_SUBTOPIC_FAIL = "FETCH_SUBTOPIC_FAIL";

export const FETCH_LECTURE_LIST_SUCCESS = "FETCH_LECTURE_LIST_SUCCESS";

export const FETCH_LECTURE_LIST_FAIL = "FETCH_LECTURE_LIST_FAIL";

export const FETCH_LECTURE_SUCCESS = "FETCH_LECTURE_SUCCESS";

export const FETCH_LECTURE_FAIL = "FETCH_LECTURE_FAIL";
// *******************END coursesAction***************

// *******************OnlinecoursesAction***************
export const CREATE_SUBSCRIPTION = "CREATE_SUBSCRIPTION";

export const FETCH_SUB_SUCCESS = "FETCH_SUB_SUCCESS";

export const FETCH_SUB_FAIL = "FETCH_SUB_FAIL";

export const GENERATEd_SUB_PAYMENT_ID = "GENERATEd_SUB_PAYMENT_ID";

// *******************END OnlinecoursesAction***************

export const SUBSCRIPTION_LOGIN = "SUBSCRIPTION_LOGIN";

export const ASK_QUESTION = "ASK_QUESTION";

export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";

export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";

export const FETCH_USER_DETAILS_LOADER = "FETCH_USER_DETAILS_LOADER";

export const UPLOAD_PROFILE = "UPLOAD_PROFILE";

// ******************* publisherAction **************
export const GET_PUBLISHER_BOOKS = "GET_PUBLISHER_BOOKS";
export const GET_FILTER_PUBLISHER_BOOKS = "GET_FILTER_PUBLISHER_BOOKS";
export const LOADING_PUBLISHER_BOOKS = "LOADING_PUBLISHER_BOOKS";
export const GET_LOCAL_STATE_PUBLISHER_BOOKS =
  "GET_LOCAL_STATE_PUBLISHER_BOOKS";

// *******************END publisherAction **************

// -------------------START readyTosShipAction

export const FETCH_ORDER_BY_READY_TO_SHIP = "FETCH_ORDER_BY_READY_TO_SHIP";
export const FETCH_ORDER_BY_INTRANSIT = "FETCH_ORDER_BY_INTRANSIT";
export const FETCH_ORDER_BY_READY_TO_DISPATCH =
  "FETCH_ORDER_BY_READY_TO_DISPATCH";
export const REMOVEORDER_READY_TO_SHIP = "REMOVEORDER_READY_TO_SHIP";
export const REMOVEORDER_READY_TO_DISPATCH = "REMOVEORDER_READY_TO_DISPATCH";
export const REMOVEORDER_INTRANSIT = "REMOVEORDER_INTRANSIT";
export const SEARCH_R_TO_SHIP_ORDER = "SEARCH_R_TO_SHIP_ORDER";
export const REMOVE_SEARCH = "REMOVE_SEARCH";
export const UPDATE_ESCALATION_RTS_ORDER = "UPDATE_ESCALATION_RTS_ORDER";
export const UPDATE_ESCALATION_TRN_ORDER = "UPDATE_ESCALATION_TRN_ORDER";
export const UPDATE_EMAIL_SEND_RTS_ORDER = "UPDATE_EMAIL_SEND_RTS_ORDER";
export const UPDATE_EMAIL_SEND_TRN_ORDER = "UPDATE_EMAIL_SEND_TRN_ORDER";
// export const FETCH_ORDER_BY_STATUS = 'FETCH_ORDER_BY_STATUS'
// ------------BackendRtoAction
export const FETCH_RTO_INITIATED_ORDERS = "FETCH_RTO_INITIATED_ORDERS";
export const LOADING_RTO_INITIATED_ORDERS = "LOADING_RTO_INITIATED_ORDERS";
export const REMOVEORDER_RTO_INITIATED = "REMOVEORDER_RTO_INITIATED";

// ------------End BackendRtoAction

// -----------Fetching backend Online course dashboard
export const FETCH_SUBSCRIBER = "FETCH_SUBSCRIBER";
export const FETCH_SUBSCRIBER_FAILED = "FETCH_SUBSCRIBER_FAILED";
export const SEARCH_SUBSCRIBER = "SEARCH_SUBSCRIBER";
// ----------- END Fetching backend Online course dashboard

// -----------bookImageAction
export const GET_BOOK_IMAGE = "GET_BOOK_IMAGE";
export const REPLACE_BOOK_IMAGE = "REPLACE_BOOK_IMAGE";

// ----------- END bookImageAction

// ----- Adding WishList  Features
export const ADDWISHLIST = "ADDWISHLIST";
export const LOADER_WISHLIST = "LOADER_WISHLIST";
export const FETCHING_WISHLIST = "FETCHING_WISHLIST";
export const FETCH_WISHLOADER = "FETCH_WISHLOADER";

export const UPDATE_WISHLIST = "UPDATE_WISHLIST";
export const ADDINGCART_WISHLIST = "ADDINGCART_WISHLIST";
export const MOVE_CART_LOADER = "MOVE_CART_LOADER";
export const REMOVE_WISHLIST = "REMOVE_WISHLIST";
export const DELETE_WISHLIST = "DELETE_WISHLIST";
export const FETCHWISHLIST_DATA = "FETCHWISHLIST_DATA";
export const DELETE_ALL = "DELETE_ALL";

//  Quora dashboard
export const FETCHREQUESTED_ACCOUNT = "FETCHREQUESTED_ACCOUNT";
export const APPROVED_ACCOUNT = "APPROVED_ACCOUNT";
export const ADD_QUORA_QUESTION = "ADD_QUORA_QUESTION";
export const FETCH_QUORA_DETAILS = "FETCH_QUORA_DETAILS";
export const FETCH_EACHCONTENT = "FETCH_EACHCONTENT";
export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const CHECK_QUESTION = "CHECK_QUESTION";
export const MAKE_PAYMENT = "MAKE_PAYMENT";
export const TOTAL_VALUE = "TOTAL_VALUE";
export const REMITTANCE_VALUE = "REMITTANCE_VALUE";
export const COMMON_QUESTIONS = "COMMON_QUESTIONS";
export const ASSIGN_MSG = "ASSIGN_MSG";
export const REMITTANCE_LOG = "REMITTANCE_LOG";
export const CHECK_ANSWER = "CHECK_ANSWER";
export const FETCH_ALL_PAYMENT = "FETCH_ALL_PAYMENT";
// Donation forms

export const PICKUPDATES = "PICKUPDATES";

// dataentysalebydaterangeAction
export const GOT_IMG_SELECTOR_DATA = "GOT_IMG_SELECTOR_DATA";

// Login Check User

export const CHECK_LOGIN_USERMSG = "CHECK_LOGIN_USERMSG";

// Data Entry Report
export const DATA_ENTRY_REPORT = "DATA_ENTRY_REPORT";

//mypustak support
export const FETCH_SUPPORT_LIST = "FETCH_SUPPORT_LIST";
export const FETCH_EACHSUPPORT_LIST = "FETCH_EACHSUPPORT_LIST";
export const SEARCH_SUPPORT_LIST = "SEARCH_SUPPORT_LIST";
export const SEND_MAIL_TO_CUSTOMER = "SEND_MAIL_TO_CUSTOMER";

export const DONATION_DETAILS = "DONATION_DETAILS";

//  Courier Invoice
export const COURIER_INVOICE_FETCH = "COURIER_INVOICE_FETCH";

// Transactions Details
export const CREATE_LEDGER = "CREATE_LEDGER";
export const FETCH_LEDGER = "FETCH_LEDGER";
export const CREATE_TRANSACTION = "CREATE_TRANSACTION";
export const FETCH_TRANSACTION_DETAIL = "FETCH_TRANSACTION_DETAIL";
export const FETCH_TRANSACTION_POINT = "FETCH_TRANSACTION_POINT";
export const FETCH_RULES_TABEL = "FETCH_RULES_TABEL";
export const FETCH_TXN_POINT = "FETCH_TXN_POINT";
export const FETCH_BANK_STATEMENT = "FETCH_BANK_STATEMENT";
export const FETCH_LEDGER_REPORT = "FETCH_LEDGER_REPORT";
export const FETCH_INVOICE_REPORT = "FETCH_INVOICE_REPORT";
export const FETCH_CREDITNOTE_REPORT = "FETCH_CREDITNOTE_REPORT";
export const FETCH_DONATION_CREDITNOTE_REPORT =
  "FETCH_DONATION_CREDITNOTE_REPORT";
export const FETCH_COURIER_ERROR = "FETCH_COURIER_ERROR";
export const FETCH_PAYMENT_ERROR = "FETCH_PAYMENT_ERROR";
export const FETCH_BANK_STATEMENT_ERROR = "FETCH_BANK_STATEMENT_ERROR";
export const FETCH_RULES_TABEL_BYTXN = "FETCH_RULES_TABEL_BYTXN";
export const FECTH_TXNPOINT_STATUS = "FECTH_TXNPOINT_STATUS";
export const FECTH_RULES_BYLEDGER = "FECTH_RULES_BYLEDGER";
export const CREATE_MANUAL_TRANSACTION = "CREATE_MANUAL_TRANSACTION";

export const FECTH_DONATION_TXNPOINT_STATUS = "FECTH_DONATION_TXNPOINT_STATUS";
export const CREATE_LEDGER_HEAD = "CREATE_LEDGER_HEAD";
export const FETCH_LEDGER_HEAD = "FETCH_LEDGER_HEAD";
export const FETCH_EACH_LEDGER_REPORT = "FETCH_EACH_LEDGER_REPORT";
export const FETCH_KEYWORD_BANKRULE = "FETCH_KEYWORD_BANKRULE";

// Donation Tracking detail
export const FETCH_DONATION_TRACKING = "FETCH_DONATION_TRACKING";

export const FETCH_WALLET_REF = "FETCH_WALLET_REF";
export const SENTDONATION_MAIL = "SENTDONATION_MAIL";
export const FLAG_USER = "FLAG_USER";
export const FETCH_WALLET_TXNENTRY = "FETCH_WALLET_TXNENTRY";

export const CREATE_MANUAL_TRANSACTION_WALLET =
  "CREATE_MANUAL_TRANSACTION_WALLET";
export const FILTER_NOT_TXNORDER = "FILTER_NOT_TXNORDER";
export const FILTER_NOT_TXNDONATION = "FILTER_NOT_TXNDONATION";
export const FETCH_WALLET_NOTXN = "FETCH_WALLET_NOTXN";
export const FETCH_ORDER_NOTXN = "FETCH_ORDER_NOTXN";
export const FETCH_DONATION_NOTXN = "FETCH_DONATION_NOTXN";
export const FETCH_USERWALLET_NOTXN = "FETCH_USERWALLET_NOTXN";

// Clear Proud Donor
export const CLEAR_PROUD_DONOR = "CLEAR_PROUD_DONOR";

export const QUEUE_NO = "QUEUE_NO";

// ADD CARTLEN
export const CARTLEN = "CARTLEN";

export const GETWALLET_REUNDLIST = "GETWALLET_REUNDLIST";
export const GETORDER_REUNDLIST = "GETORDER_REUNDLIST";
export const GETDONATION_REUNDLIST = "GETDONATION_REUNDLIST";
export const REFUND_WALLET_SEARCH = "REFUND_WALLET_SEARCH";
export const REFUND_WALLET_SEARCH_ORDER = "REFUND_WALLET_SEARCH_ORDER";
export const UPDATE_REFUND_STATUS = "UPDATE_REFUND_STATUS";
export const UPDATE_NOREFUND_STATUS = "UPDATE_NOREFUND_STATUS";

export const GETFAILEDORDERLIST = "GETFAILEDORDERLIST";
export const FAILEDORDERISLOADING = "FAILEDORDERISLOADING";

export const UPDATE_ORDER_REFUND_STATUS = "UPDATE_ORDER_REFUND_STATUS";
export const UPDATE_ORDER_NOREFUND_STATUS = "UPDATE_ORDER_NOREFUND_STATUS";
export const UPDATE_DONATION_REFUND_STATUS = "UPDATE_DONATION_REFUND_STATUS";
export const UPDATE_DONATION_NOREFUND_STATUS =
  "UPDATE_DONATION_NOREFUND_STATUS";

// Book Inventory Audit rack
export const AUDIT_RACKS = "AUDIT_RACKS";
export const AUDIT_DETAILRACKS = "AUDIT_DETAILRACKS";

export const FETCH_EMPLOYEEDATA = "FETCH_EMPLOYEEDATA";
export const FETCH_EMPLOYEE_ATTENDANCE_RECORD =
  "FETCH_EMPLOYEE_ATTENDANCE_RECORD";
export const FETCH_EMPLOYEE_CLOCKEDIN = "FETCH_EMPLOYEE_CLOCKEDIN";
export const FETCH_EMPLOYEE_DETAIL = "FETCH_EMPLOYEE_DETAIL";

export const FETCH_SALARY_DATA = "FETCH_SALARY_DATA";
export const CREATE_EMP_DETAIL_REPORT = "CREATE_EMP_DETAIL_REPORT";
export const SEARCH_EMPLOYEE_DETAILS = "SEARCH_EMPLOYEE_DETAILS";
export const FILTER_EMPLOYEE_DETAILS = "FILTER_EMPLOYEE_DETAILS";

// Vendor Types

export const VENDOR_DETAILS = "VENDOR_DETAILS";
export const UPDATE_BASICDETAILS = "UPDATE_BASICDETAILS";

export const VENDOR_SEARCHLIST = "VENDOR_SEARCHLIST";
export const VENDOR_GETLIST = "VENDOR_GETLIST";
export const VENDOR_BOOKDATA = "VENDOR_BOOKDATA";
export const CLEAR_BOOKDATA = "CLEAR_BOOKDATA";
export const VENDOR_ALLORDER = "VENDOR_ALLORDER";
export const VENDOR_WALLET_ORDER = "VENDOR_WALLET_ORDER";
export const CLEAR_ORDERDATA = "CLEAR_ORDERDATA";
export const VENDOR_ORDERBOOK = "VENDOR_ORDERBOOK";
export const VENDOR_ALLWALLET_TRANSACTION = "VENDOR_ALLWALLET_TRANSACTION";
export const VENDOR_ALLREMITTANCE = "VENDOR_ALLREMITTANCE";
export const VENDOR_WALLETINFO = "VENDOR_WALLETINFO";
export const DASHBOARD_DATA = "DASHBOARD_DATA";
export const FETCH_PICKUPINVOICE_REPORT = "FETCH_PICKUPINVOICE_REPORT";
export const FETCH_STATUS_DATA = "FETCH_STATUS_DATA";
export const FETCH_ADMIN_STATUS_DATA = "FETCH_ADMIN_STATUS_DATA";
export const FETCH_STATUS_DATA1 = "FETCH_STATUS_DATA1";
export const TRACKING_ALERT = "TRACKING_ALERT";
export const PICKUP_ALERT = "PICKUP_ALERT";

//vendor admin

export const VIEW_VENDORS = "VIEW_VENDORS";
export const VIEW_BOOKS = "VIEW_BOOKS";
export const VIEW_ADMIN_BOOKS = "VIEW_ADMIN_BOOKS";
export const VENDOR_ADMIN_VIEW_VENDORS = "VENDOR_ADMIN_VIEW_VENDORS";
export const VENDOR_ADMIN_VIEW_BOOKS = "VENDOR_ADMIN_VIEW_BOOKS";
export const VENDOR_ADMIN_VIEW_BOOKS_IS_PUBLISHED =
  "VENDOR_ADMIN_VIEW_BOOKS_IS_PUBLISHED";

export const VENDOR_ADMIN_VIEW_BOOKS_VIEW_DETAIL =
  "VENDOR_ADMIN_VIEW_BOOKS_VIEW_DETAIL";

export const VENDOR_ADMIN_VIEW_VENDOR_VIEW_DETAIL =
  "VENDOR_ADMIN_VIEW_VENDOR_VIEW_DETAIL";

export const VENDOR_ORDER_VIEW_DETAIL = "VENDOR_ORDER_VIEW_DETAIL";
export const VENDOR_BOOK_DETAIL = "VENDOR_BOOK_DETAIL";
export const VENDOR_CHECK_ORDER_DENIED = "VENDOR_CHECK_ORDER_DENIED";
export const VENDOR_GET_CARRIER_PARTNERS = "VENDOR_GET_CARRIER_PARTNERS";

export const VENDOR_GET_DETAILS_SHIPROCKET = "VENDOR_GET_DETAILS_SHIPROCKET";
export const VENDOR_GET_DETAILS_SHIPROCKET_WRAPPER =
  "VENDOR_GET_DETAILS_SHIPROCKET_WRAPPER";
export const VENDOR_GET_DETAILS_SHIPROCKET_PICKUP =
  "VENDOR_GET_DETAILS_SHIPROCKET_PICKUP";
export const VENDOR_SHIPROCKET_WRAPPER = "VENDOR_SHIPROCKET_WRAPPER";

export const VENDOR_VIEW_VENDORS = "VENDOR_VIEW_VENDORS";

// OFFER PAGE TYPES
export const GETOFFERS = "GETOFFERS";
export const GETOFFERSHOME = "GETOFFERSHOME";
export const VENDOR_GET_DETAILS_UPLOAD_BOOKS =
  "VENDOR_GET_DETAILS_UPLOAD_BOOKS";
export const RTD_LOADER_TOGGLE = "RTD_LOADER_TOGGLE";
export const CREATE_EMP_REPORT = "CREATE_EMP_REPORT";
export const MAKE_CLOCKOUT = "MAKE_CLOCKOUT";
export const MAKE_CLOCKIN = "MAKE_CLOCKIN";
export const SEARCH_REFUND_ORDER = "SEARCH_REFUND_ORDER";
export const SEARCH_REFUND_WALLET = "SEARCH_REFUND_WALLET";
export const SEARCH_REFUND_DONATION = "SEARCH_REFUND_DONATION";
// export const VENDOR_GET_DETAILS_UPLOAD_BOOKS = "VENDOR_GET_DETAILS_UPLOAD_BOOKS";
export const VENDOR_UPDATE_SHIPMENT_DETAIL = "VENDOR_UPDATE_SHIPMENT_DETAIL";
export const VENDOR_FETCH_EXCEL_FILE = "VENDOR_FETCH_EXCEL_FILE";
export const VENDOR_FETCH_ALL_EXCEL_FILE = "VENDOR_FETCH_ALL_EXCEL_FILE";
export const VENDOR_FETCH_ALL_ORDERS = "VENDOR_FETCH_ALL_ORDERS";
export const VENDOR_VIEW_BOOKS_IS_PUBLISHED = "VENDOR_VIEW_BOOKS_IS_PUBLISHED";
export const UPDATE_PRODUCT_DATA = "UPDATE_PRODUCT_DATA";
export const SEARCH_VIEW_BOOK = "SEARCH_VIEW_BOOK";
export const VENDOR_UPDATE_STATUS = "VENDOR_UPDATE_STATUS";
export const VENDOR_ADMIN_ALLWALLET_TRANSACTION =
  "VENDOR_ADMIN_ALLWALLET_TRANSACTION";
export const FETCH_ORDER_BY_VENDOR = "FETCH_ORDER_BY_VENDOR";
export const FETCH_REMITTANCE = "FETCH_REMITTANCE";
export const FETCH_REMITTANCE_BY_VENDORID = "FETCH_REMITTANCE_BY_VENDORID";
export const FETCH_REMITTANCE_ADMIN_BY_VENDORID =
  "FETCH_REMITTANCE_ADMIN_BY_VENDORID";

export const FETCH_ORDER_BY_LOST = "FETCH_ORDER_BY_LOST";
export const REMOVEORDER_LOST = "REMOVEORDER_LOST";

export const ACTIVITY_LOG_ORDERID = "ACTIVITY_LOG_ORDERID";
export const ACTIVITY_DRAWER = "ACTIVITY_DRAWER";
export const VIEW_GATEWAY_PAYMENT = "VIEW_GATEWAY_PAYMENT";
export const ROUTEMAP = "ROUTEMAP";

export const SUBJECTS = "SUBJECTS";
export const NEWBOOKINGFORPICKUP = "NEWBOOKINGFORPICKUP";
export const SELECTBOOKINGCOURIER = "SELECTBOOKINGCOURIER";

export const SELF_PICKUP = "SELF_PICKUP";
export const SELF_PICKUP_SELECT = "SELF_PICKUP_SELECT";
export const SELF_PICKUP_SEARCH = "SELF_PICKUP_SEARCH";
export const SELF_PICKUP_UPDATE_STATUS = "SELF_PICKUP_UPDATE_STATUS";
export const REMITANCE_DATA = "REMITANCE_DATA_ALL";
export const REMITANCE_MONTHS_DATA = "REMITANCE_MONTHS_DATA_ALL";
export const REMITANCE_EMPID_DATA = "REMITANCE_ID_DATA_ALL";
export const REMITANCE_EMAIL_DATA = "REMITANCE_EMAIL_DATA_ALL";
export const REMITANCE_ALLMONTHS_DATA = "REMITANCE_ALLMONTHS_DATA";
export const FAQ_FETCH_ALL_DATA = "FAQ_FETCH_ALL_DATA";
export const FAQ_FETCH_BY_FAQID = "FAQ_FETCH_BY_FAQID";
export const FAQ_FETCH_BY_FAQCATEGORY = "FAQ_FETCH_BY_FAQCATEGORY";
export const FAQ_FETCH_ALL_CATEGORY_DATA = "FAQ_FETCH_ALL_CATEGORY_DATA";
export const FILTER_ORDER_REFUND = "FILTER_ORDER_REFUND";
export const COURIER_INVOICE_SEARCH = "COURIER_INVOICE_SEARCH";
export const COURIER_INVOICE_FILTER = "COURIER_INVOICE_FILTER";
export const CORIERINVOICEERORRDATA = "CORIERINVOICEERORRDATA";
// ORDER INVOICE TYPE
export const FETCHALLORDERINVOICE = "FETCHALLORDERINVOICE";
export const FETCHSEARCHORDERINVOICE = "FETCHSEARCHORDERINVOICE";
export const GETORDERDETAILSINCI = "GETORDERDETAILSINCI";
export const GETEVERYORDERDETAILS = "GETEVERYORDERDETAILS";
// cod_reconciliation
export const GETALLCODRECONCILATIONDATA = "GETALLCODRECONCILATIONDATA";
export const GETSEARCHCODRECONCILATIONDATA = "GETSEARCHCODRECONCILATIONDATA";
export const GETFILTERCODRECONCILATIONDATA = "GETFILTERCODRECONCILATIONDATA";
export const CODRECONCILATIONERORRDATA = "CODRECONCILATIONERORRDATA";

// Data Entry Report
export const BOOK_FOUND_REPORT = "BOOK_FOUND_REPORT";
export const BOOK_PACKED_REPORT = "BOOK_PACKED_REPORT";

export const FILTERORDERBOOKS = "FILTERORDERBOOKS";

// donation invoice
export const ALLDONATIONINVOICEDATA = "ALLDONATIONINVOICEDATA";
export const SEARCHDONATIONINVOICEDATA = "SEARCHDONATIONINVOICEDATA";
export const GETLENGTH = "GETLENGTH";
export const ORDERDETAILSINTIAL = "ORDERDETAILSINTIAL";
export const ORDERDETAILSINTIALDATA = "ORDERDETAILSINTIALDATA";
export const ISSERVERERROR = "ISSERVERERROR";

export const IS_OFFER_BOOK = "IS_OFFER_BOOK";
export const GETREVIEW = "GETREVIEW";
export const GETREVIEWBYPRODUCT = "GETREVIEWBYPRODUCT";
export const ADDREVIEW = "ADDREVIEW";
export const WISHLISTCOUNT = "WISHLISTCOUNT";
export const UPDATE_WISHLIST_CONDITION = "UPDATE_WISHLIST_CONDITION";
export const APPLY_COUPONCODE = "APPLY_COUPONCODE";

export const UNBOX_SEARCH = "UNBOX_SEARCH";
export const UNBOX_AUTOCOMPLETE = "UNBOX_AUTOCOMPLETE";
export const UNBOX_PUBLICATION = "UNBOX_PUBLICATION";
export const UNBOX_AUTHOR = "UNBOX_AUTHOR";
export const CLEAR_AUTOSUGGEST = "CLEAR_AUTOSUGGEST";
export const UNBOX_FILTER_APPLIED = "UNBOX_FILTER_APPLIED";
export const TOOGLE_GLOBAL_SEARCHLOADER = "TOOGLE_GLOBAL_SEARCHLOADER";

export const WALLETRECHARGEOFFERS = "WALLETRECHARGEOFFERS";
export const SHOWCONFETTI = "SHOWCONFETTI";
export const fETCH_COMMUNICATE_PREFERENCE = "fETCH_COMMUNICATE_PREFERENCE"
export const UNBOX_RECOMMENDATIONS = "UNBOX_RECOMMENDATIONS"
export const SETBOOKFORPOPUPMSG = "SETBOOKFORPOPUPMSG"
export const ClEARBOOKFORPOPUPMSG = "ClEARBOOKFORPOPUPMSG"
export const SHOW_AUTOSUGGEST_DIALOG = "SHOW_AUTOSUGGEST_DIALOG"
export const NEWGETUPDATEDORDERD = "NEWGETUPDATEDORDERD";
export const NEWGETORDERD = "NEWGETORDERD";
export const FREEBIE_DATA = "FREEBIE_DATA";
export const FREEBIE_LOADER = "FREEBIE_LOADER";

// mypustak blogs 
export const GETACTIVEBLOG = "GETACTIVEBLOG";
export const GETACTIVECATEGORY = "GETACTIVECATEGORY";
export const GETACTIVETAGS = "GETACTIVETAGS";
export const GETCATEGORYDATA = "GETCATEGORYDATA";
export const GETBLOGDETAILS = "GETBLOGDETAILS";
export const GET_TAG_BY_SLUG = "GET_TAG_BY_SLUG";
export const GET_POST_BY_USER ="GET_POST_BY_USER";
export const USER_POST_BY_SLUG ="USER_POST_BY_SLUG";
export const GET_CATEGORIES ="GET_CATEGORIES";
export const GET_BLOG_BY_ID = "GET_BLOG_BY_ID";
export const GET_USER_DETAILS = "GET_USER_DETAILS";




